Repository getPopsure/dirty-swan, pull requests merged in 2023-06, with the labels that each got.

#222 docs(autocomplete-address): [EMU-6207] Update documentation to use storybook controls
  src/lib/components/autocompleteAddress/demo.tsx
  src/lib/components/autocompleteAddress/index.stories.mdx
  src/lib/components/autocompleteAddress/index.stories.tsx
  src/lib/components/autocompleteAddress/index.test.tsx
  src/lib/components/autocompleteAddress/index.tsx
  src/lib/components/segmentedControl/index.stories.tsx
  src/lib/index.tsx
Labels: documentation

#224 feat(images): Add images assets folder
  assets/images/aid.svg
  assets/images/bed.svg
  assets/images/bigDog.svg
  assets/images/brokenAquarium.svg
  assets/images/brokenGlass.svg
  assets/images/damagedLaptop.svg
  assets/images/moneyIncome.svg
  assets/images/washingMachine.svg
Labels: Feature

#225 feat(images): Add images list export
  src/index.tsx
  src/lib/index.tsx
  src/lib/util/images/index.stories.tsx
  src/lib/util/images/index.ts
Labels: Feature

#226 docs(component): Add storybook controls to SignaturePad and DownloadButton components
  src/App.tsx
  src/lib/components/downloadButton/index.stories.mdx
  src/lib/components/downloadButton/index.stories.tsx
  src/lib/components/downloadButton/index.tsx
  src/lib/components/signaturePad/index.stories.mdx
  src/lib/components/signaturePad/index.stories.tsx
  src/lib/components/signaturePad/index.tsx
  src/lib/index.tsx
Labels: documentation

#227 docs(markdown): [EMU-6214] Add storybook controls to Markdown component
  src/global.d.ts
  src/lib/components/markdown/index.stories.mdx
  src/lib/components/markdown/index.stories.tsx
  src/lib/components/markdown/index.tsx
  src/lib/index.tsx
Labels: documentation

#229 fix(markdown): Remove .md definitions
  src/global.d.ts
  src/lib/components/markdown/example.md
  src/lib/components/markdown/index.stories.tsx
Labels: Fix

#230 fix(checkbox): Fix max width on mobile
  src/lib/components/input/checkbox/index.tsx
  src/lib/components/input/checkbox/styles.module.scss
Labels: Fix

#231 fix(checkbox): Update checkbox to use max-width instead of width
  src/lib/components/input/checkbox/index.tsx
  src/lib/components/input/checkbox/styles.module.scss
Labels: Fix

#232 docs(modal): Add storybook controls to Modal stories
  src/lib/components/modal/bottomModal/index.tsx
  src/lib/components/modal/bottomOrRegularModal/index.tsx
  src/lib/components/modal/index.stories.mdx
  src/lib/components/modal/index.stories.tsx
  src/lib/components/modal/index.ts
  src/lib/components/modal/regularModal/index.tsx
Labels: documentation

#233 feat(icons): add icons
  assets/images/dogLiabilityIcon.png
  assets/images/dogLiabilityIcon2x.png
  assets/images/dogLiabilityIcon3x.png
  src/lib/util/images/index.stories.tsx
  src/lib/util/images/index.ts
Labels: Feature

#235 docs(date-selector): Add storybook controls to DateSelector stories
  src/App.tsx
  src/lib/components/dateSelector/index.stories.mdx
  src/lib/components/dateSelector/index.stories.tsx
  src/lib/components/dateSelector/index.test.tsx
  src/lib/components/dateSelector/index.tsx
  src/lib/index.tsx
Labels: documentation

#236 docs(multi-dropzone): Add storybook controls to MultiDropzone stories
  src/lib/components/multiDropzone/index.stories.mdx
  src/lib/components/multiDropzone/index.stories.tsx
  src/lib/components/multiDropzone/index.test.tsx
  src/lib/components/multiDropzone/index.tsx
  src/lib/index.tsx
Labels: documentation

#237 chore(icons): Add more icons
  assets/images/bill.svg
  assets/images/books.svg
  assets/images/finalExpenses.svg
  assets/images/lifeIcon.png
  assets/images/lifeIcon2x.png
  assets/images/lifeIcon3x.png
  assets/images/mortgage.svg
  src/lib/util/images/index.ts
Labels: Chore

#238 docs(cards): Add storybook controls to Cards stories
  src/lib/components/cards/cardButton/index.stories.mdx
  src/lib/components/cards/cardButton/index.stories.tsx
  src/lib/components/cards/cardButton/index.tsx
  src/lib/components/cards/cardWithLeftIcon/index.stories.mdx
  src/lib/components/cards/cardWithLeftIcon/index.stories.tsx
  src/lib/components/cards/cardWithLeftIcon/index.tsx
  src/lib/components/cards/cardWithTopIcon/index.stories.mdx
  src/lib/components/cards/cardWithTopIcon/index.stories.tsx
  src/lib/components/cards/cardWithTopIcon/index.tsx
  src/lib/components/cards/cardWithTopLeftIcon/index.stories.mdx
  src/lib/components/cards/cardWithTopLeftIcon/index.stories.tsx
  src/lib/components/cards/cardWithTopLeftIcon/index.tsx
  src/lib/components/cards/index.tsx
  src/lib/components/cards/infoCard/index.stories.mdx
  src/lib/components/cards/infoCard/index.stories.tsx
  src/lib/components/cards/infoCard/index.tsx
Labels: documentation
