Repository getPopsure/dirty-swan, pull requests merged in 2023-10, with the labels that each got.

#271 refactor(icon): [STO-6158] replace internal icons with Icon component
  src/lib/components/cards/cardButton/index.tsx
  src/lib/components/cards/cardButton/style.module.scss
  src/lib/components/cards/icons/chevron-right.svg
  src/lib/components/cards/icons/index.ts
  src/lib/components/chip/icons/remove-button-highlighted.svg
  src/lib/components/chip/icons/remove-button.svg
  src/lib/components/chip/index.tsx
  src/lib/components/chip/style.module.scss
  src/lib/components/dateSelector/icons/calendar.svg
  src/lib/components/dateSelector/index.test.tsx
  src/lib/components/dateSelector/index.tsx
  src/lib/components/dateSelector/style.module.scss
  src/lib/components/downloadButton/icons/check.svg
  src/lib/components/downloadButton/index.tsx
  src/lib/components/informationBox/index.tsx
  src/lib/components/informationBox/style.module.scss
  src/lib/components/modal/bottomModal/index.tsx
  src/lib/components/modal/bottomModal/style.module.scss
  src/lib/components/modal/regularModal/index.tsx
  src/lib/components/modal/regularModal/style.module.scss
  src/lib/components/multiDropzone/UploadFileCell/index.tsx
  src/lib/components/multiDropzone/UploadFileCell/style.module.scss
  src/lib/components/multiDropzone/icons/eye.svg
  src/lib/components/multiDropzone/icons/file-error.svg
  src/lib/components/multiDropzone/icons/file-upload.svg
  src/lib/components/multiDropzone/icons/file.svg
  src/lib/components/multiDropzone/icons/index.ts
  src/lib/components/multiDropzone/icons/trash-error.svg
  src/lib/components/multiDropzone/icons/trash.svg
  src/lib/components/multiDropzone/icons/upload-small.svg
  src/lib/components/multiDropzone/icons/upload.svg
  src/lib/components/multiDropzone/index.test.tsx
  src/lib/components/multiDropzone/index.tsx
Labels: Refactor

#273 refactor(input): [STO-6165] update type for checkbox and radio options
  src/lib/components/input/checkbox/index.test.tsx
  src/lib/components/input/checkbox/index.tsx
  src/lib/components/input/radio/index.test.tsx
  src/lib/components/input/radio/index.tsx
Labels: Refactor

#275 fix(toggle): Add disabled state to Toggle component
  src/lib/components/input/toggle/index.stories.tsx
  src/lib/components/input/toggle/index.tsx
Labels: Fix

#274 feat(toast): Add toast component/util
  package.json
  src/index.tsx
  src/lib/components/toast/index.stories.tsx
  src/lib/components/toast/index.test.tsx
  src/lib/components/toast/index.tsx
  src/lib/components/toast/style.module.scss
  src/lib/index.tsx
  yarn.lock
Labels: Feature

#277 fix(radio): Add prop to allow inline icon option to custom icon
  src/lib/components/input/radio/index.stories.tsx
  src/lib/components/input/radio/index.tsx
Labels: Fix

#278 feat(illustrations): Add illustrations assets list
  assets/images/aid.svg
  assets/images/bed.svg
  assets/images/bigDog.svg
  assets/images/bill.svg
  assets/images/books.svg
  assets/images/brokenAquarium.svg
  assets/images/brokenGlass.svg
  assets/images/damagedLaptop.svg
  assets/images/dogLiabilityIcon.png
  assets/images/dogLiabilityIcon2x.png
  assets/images/dogLiabilityIcon3x.png
  assets/images/finalExpenses.svg
  assets/images/lifeIcon.png
  assets/images/lifeIcon2x.png
  assets/images/lifeIcon3x.png
  assets/images/moneyIncome.svg
  assets/images/mortgage.svg
  assets/images/washingMachine.svg
  src/index.tsx
  src/lib/index.tsx
  src/lib/util/images/index.stories.tsx
  src/lib/util/images/index.ts
  src/lib/util/images/style.module.scss
Labels: Feature

#279 feat(card): Add Card component
  src/lib/components/card/index.stories.tsx
  src/lib/components/card/index.tsx
  src/lib/components/card/style.module.scss
  src/lib/models/styles.ts
  src/lib/scss/public/shadows.scss
Labels: Feature

#276 feat(button): Refactor button component
  src/lib/components/button/icons/index.ts
  src/lib/components/button/icons/send-purple.svg
  src/lib/components/button/icons/send-white.svg
  src/lib/components/button/index.stories.mdx
  src/lib/components/button/index.stories.tsx
  src/lib/components/button/index.test.tsx
  src/lib/components/button/index.tsx
  src/lib/components/button/styles.module.scss
  src/lib/components/card/index.stories.tsx
  src/lib/components/comparisonTable/index.tsx
  src/lib/components/downloadButton/icons/download.svg
  src/lib/components/downloadButton/index.tsx
  src/lib/components/icon/IconWrapper/IconWrapper.tsx
  src/lib/components/icon/icons.stories.tsx
  src/lib/components/toast/index.stories.tsx
  src/lib/index.tsx
  src/lib/models/styles.ts
  src/lib/scss/private/components/_buttons.scss
  src/lib/util/images/index.stories.tsx
Labels: Feature

#280 refactor(toast): Update toast styles
  src/lib/components/toast/index.stories.tsx
  src/lib/components/toast/index.tsx
  src/lib/components/toast/style.module.scss
Labels: Refactor

#281 fix(images): Fix images types and add missing card exports
  src/index.tsx
  src/lib/index.tsx
  src/lib/util/images/index.ts
Labels: Fix
