Repository getPopsure/dirty-swan, pull requests merged in 2023-07, with the labels that each got.

#239 docs(input): Add storybook controls to Input stories
  src/lib/components/autocompleteAddress/index.tsx
  src/lib/components/input/a.stories.mdx
  src/lib/components/input/autoSuggestInput/index.tsx
  src/lib/components/input/currency/index.tsx
  src/lib/components/input/iban/index.tsx
  src/lib/components/input/index.stories.mdx
  src/lib/components/input/index.tsx
  src/lib/components/input/input.stories.tsx
  src/lib/components/input/stories/config.ts
  src/lib/index.tsx
Labels: documentation

#240 feat(color): [CHA-3977] update color p-100 value
  src/lib/scss/public/colors/default.scss
  src/lib/scss/public/demo.tsx
Labels: Feature

#241 feat(link): [EMU-5965] Add Link component
  src/index.tsx
  src/lib/components/link/index.stories.tsx
  src/lib/components/link/index.tsx
  src/lib/index.tsx
Labels: Feature

#242 refactor(auto-suggest-multi-select): [CHA-3762] Add entry animation to chip container
  src/lib/components/chip/index.tsx
  src/lib/components/input/autoSuggestMultiSelect/index.tsx
  src/lib/components/input/autoSuggestMultiSelect/style.module.scss
Labels: Refactor

#246 docs(auto-suggest): [EMU-6218] Update auto suggest inputs to use storybook controls
  src/lib/components/input/autoSuggestInput/index.stories.mdx
  src/lib/components/input/autoSuggestInput/index.stories.tsx
  src/lib/components/input/autoSuggestInput/index.tsx
  src/lib/components/input/autoSuggestMultiSelect/index.stories.mdx
  src/lib/components/input/autoSuggestMultiSelect/index.stories.tsx
  src/lib/components/input/autoSuggestMultiSelect/index.tsx
  src/lib/index.tsx
Labels: documentation

#249 refactor(card-left-icon): Update CardWithLeftIcon icon size and text
  src/lib/components/cards/cardWithLeftIcon/index.stories.tsx
  src/lib/components/cards/cardWithLeftIcon/index.tsx
Labels: Refactor

#248 feat(badge): Add Badge component
  src/index.tsx
  src/lib/components/badge/index.stories.tsx
  src/lib/components/badge/index.test.tsx
  src/lib/components/badge/index.tsx
  src/lib/components/badge/style.module.scss
  src/lib/index.tsx
  src/lib/scss/private/components/badge.stories.mdx
Labels: Feature

#251 fix(CurrencyInput): [EMU-6492] Don't exec onChange on initial render
  src/lib/components/input/currency/index.tsx
Labels: Fix
