Repository getPopsure/dirty-swan, pull requests merged in 2023-09, with the labels that each got.

#258 fix(checkbox): [EMU-4092] update vertical padding
  src/lib/scss/private/components/_input.scss
Labels: Fix

#254 feat(radio): Add Radio component
  src/index.tsx
  src/lib/components/input/radio/index.stories.tsx
  src/lib/components/input/radio/index.test.tsx
  src/lib/components/input/radio/index.tsx
  src/lib/components/input/radio/styles.module.scss
  src/lib/index.tsx
  src/lib/scss/private/components/_input.scss
Labels: Feature

#261 fix(checkbox): Add bordered prop and fix wide true size
  src/lib/components/input/checkbox/index.stories.tsx
  src/lib/components/input/checkbox/index.tsx
  src/lib/components/input/checkbox/styles.module.scss
Labels: Fix

#255 refactor(checkbox): Refactor checkbox to use classnames object
  src/lib/components/input/checkbox/index.stories.tsx
  src/lib/components/input/checkbox/index.tsx
Labels: Refactor

#260 feat(spinner): [EMU-6599] add spinner component
  src/index.tsx
  src/lib/components/spinner/index.stories.tsx
  src/lib/components/spinner/index.test.tsx
  src/lib/components/spinner/index.tsx
  src/lib/index.tsx
Labels: Feature

#262 fix(address-autocomplete): [EMU-5932] make “enter address manually" accessible
  src/lib/components/autocompleteAddress/index.test.tsx
  src/lib/components/autocompleteAddress/index.tsx
Labels: Fix

#263 fix(button): Fix type prop not being passed to button element
  src/lib/components/button/index.tsx
Labels: Fix

#259 fix(multidropzone): [EMU-5919] add label to multidropzone component
  src/lib/components/multiDropzone/index.test.tsx
  src/lib/components/multiDropzone/index.tsx
  src/lib/components/multiDropzone/style.module.scss
Labels: Fix

#264 fix(icon): Fix icon wrapper not centering SVG
  src/lib/components/icon/IconWrapper/IconWrapper.tsx
  src/lib/components/icon/IconWrapper/styles.module.scss
Labels: Fix

#265 fix(icon): Replace padding with margin
  src/lib/components/icon/IconWrapper/styles.module.scss
Labels: Fix

#267 fix(card): use div to wrap children
  src/lib/components/cards/cardWithLeftIcon/index.tsx
  src/lib/components/cards/cardWithTopLeftIcon/index.tsx
Labels: Fix

#266 fix(address): prevent infinite loop when initial address is not provided
  src/lib/components/autocompleteAddress/index.stories.tsx
  src/lib/components/autocompleteAddress/index.tsx
Labels: Fix

#268 fix(uploader): [EMU-6747] Fix file uploader cell with large names
  src/lib/components/multiDropzone/UploadFileCell/index.tsx
  src/lib/components/multiDropzone/UploadFileCell/style.module.scss
  src/lib/components/multiDropzone/index.stories.tsx
  src/lib/components/multiDropzone/index.tsx
Labels: Fix

#269 fix(modal): [EMU-6739] Fix BottomModal scrolling on safari
  src/lib/components/modal/bottomModal/index.tsx
  src/lib/components/modal/bottomModal/style.module.scss
Labels: Fix
