Repository getPopsure/dirty-swan, pull requests merged in 2024-04, with the labels that each got.

#299 fix(card): Allow always setting action icon
  src/index.tsx
  src/lib/components/card/index.stories.tsx
  src/lib/components/card/index.tsx
  src/lib/index.tsx
Labels: Fix

#300 fix(card): Fix exported CardProps
  src/lib/index.tsx
Labels: Fix

#301 feat(card): Add polymorphic as prop support to Card component
  src/lib/components/card/index.stories.tsx
  src/lib/components/card/index.tsx
  src/lib/components/card/style.module.scss
Labels: Feature

#302 fix(card): Fix and clean card polymorphic generics
  src/lib/components/card/index.tsx
Labels: Fix

#303 fix(button): Fix btn-secondary/textColor loading not showing correctly
  src/lib/components/button/index.tsx
  src/lib/scss/private/components/_buttons.scss
Labels: Fix

#306 refactor(comparison): replaced useLayoutEffect with useEffect
  src/lib/components/comparisonTable/hooks/useComparisonTable.ts
Labels: Refactor
